export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const LOAD_CHATS_START = "LOAD_CHATS_START";
export const LOAD_CHATS_SUCCESS = "LOAD_CHATS_SUCCESS";
export const LOAD_CHATS_FAIL = "LOAD_CHATS_FAIL";

export const OPEN_CHAT_START = "OPEN_CHAT_START";
export const OPEN_CHAT_SUCCESS = "OPEN_CHAT_SUCCESS";
export const OPEN_CHAT_FAIL = "OPEN_CHAT_FAIL";

export const ADD_MESSAGE = "ADD_MESSAGE";